name: Deploy main

on:
    push:
        branches:
            - main

env:
  NODE_VERSION: '20.16.0'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: dist

    deploy:
        name: Deploy 🚀
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: dist

            - name: Upload artifact via ssh
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  target: /var/www/alpimi
                  source: dist
                  strip_components: 1
                  rm: true
